const sunriseNoonSunsetMidnight = require('../index');
sunriseNoonSunsetMidnight.init(44.4056, 8.9463);
const sunrise = sunriseNoonSunsetMidnight.sunrise();
const noon = sunriseNoonSunsetMidnight.noon();
const sunset = sunriseNoonSunsetMidnight.sunset();
const midnight = sunriseNoonSunsetMidnight.midnight();
console.log(`Sunrise: ${sunrise.getHours()}:${sunrise.getMinutes()} ${sunrise.getDate()}-${sunrise.getMonth()+1}`);
console.log(`Noon: ${noon.getHours()}:${noon.getMinutes()} ${noon.getDate()}-${noon.getMonth()+1}`);
console.log(`Sunset: ${sunset.getHours()}:${sunset.getMinutes()} ${sunset.getDate()}-${sunset.getMonth()+1}`);
console.log(`Midnight: ${midnight.getHours()}:${midnight.getMinutes()} ${midnight.getDate()}-${midnight.getMonth()+1}`);
console.log(`Is Day: ${sunriseNoonSunsetMidnight.isDay()}`);